matrix:
  include:


  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - QT_BRANCH=5.6
    - QT_VER=5.6.3
    - QT_INSTALLER_FILE=qt-opensource-mac-x64-clang-5.6.3

  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - QT_BRANCH=5.9
    - QT_VER=5.9.3
    - QT_INSTALLER_FILE=qt-opensource-mac-x64-5.9.3
    - LIBCLANG_FILE=libclang-release_39-mac.7z




before_install:
  # Python 3.5
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ec545d45d4512ace3570782283df4ecda6bb0044/Formula/python3.rb

  # lxml
  - brew install libxslt libxml2

  # 7zip
  - brew install p7zip

  # Qt 5.9
  - curl -L -O https://download.qt.io/archive/qt/${QT_BRANCH}/${QT_VER}/${QT_INSTALLER_FILE}.dmg
  - hdiutil attach -noverify ${QT_INSTALLER_FILE}.dmg
  - travis_wait 30 /Volumes/${QT_INSTALLER_FILE}/${QT_INSTALLER_FILE}.app/Contents/MacOS/${QT_INSTALLER_FILE} --script qt-installer-${QT_VER}-noninteractive.qs --verbose -platform minimal
  - ls -alh ~/Qt

  # libclang
  - if [ "$QT_BRANCH" == "5.9" ]; then curl -L -O http://download.qt.io/development_releases/prebuilt/libclang/${LIBCLANG_FILE} ;
  - if [ "$QT_BRANCH" == "5.9" ]; then 7z x ${LIBCLANG_FILE} ;
  - if [ "$QT_BRANCH" == "5.9" ]; then export LLVM_INSTALL_DIR=$(pwd)/libclang ;

  # OpenSSL already provided by Travis CI
  # - brew install openssl
  # https://github.com/travis-ci/travis-ci/issues/6698#issuecomment-252540860
  # - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi'

  # CMake 3.0 already provided by Travis CI
  # - brew install cmake

before_script:
  # Fix "fatal error: 'type_traits' file not found"
  # - export CPLUS_INCLUDE_PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/"

  # Fix "clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]"
  # - export CLANG_CXX_LIBRARY="libc++"

  - git clone --recursive --branch ${QT_BRANCH} https://code.qt.io/pyside/pyside-setup.git ~/pyside-setup

script:
  # Note, redacted --openssl=/usr/local/Cellar/openssl/1.0.2h_1/bin
  - python3 ~/pyside-setup/setup.py bdist_wheel --ignore-git --standalone --no-examples --qmake=$HOME/Qt/${QT_VER}/clang_64/bin/qmake --cmake=/usr/local/bin/cmake --jobs=3


# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy:
# after_script:
