matrix:
  include:


  # OS X 10.10, Xcode 8.3, Qt 5.6, Python 3.5
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - RVM_CERT_FIX=1
    - QT_VER=5.6
    - PY_VER=3.5


before_install:
  - curl -L -O https://download.qt.io/archive/qt/5.9/5.9.3/qt-opensource-mac-x64-5.9.3.dmg
  - hdiutil attach qt-opensource-mac-x64-5.9.3.dmg
  # Install script from: https://stackoverflow.com/questions/25105269/silent-install-qt-run-installer-on-ubuntu-server
  - /Volumes/qt-opensource-mac-x64-5.9.3/qt-opensource-mac-x64-5.9.3.app/Contents/MacOS/qt-opensource-mac-x64-5.9.3 --script qs-installer-noninteractive.qs --verbose


# before_script:
# after_script:
# script:
# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy:
# after_script:
